name: xarray-leaflet
channels:
  - conda-forge
dependencies:
  - requests
  - tqdm
  - scipy
  - dask
  - pip
  - pip:
    - git+https://github.com/davidbrochart/xarray_leaflet.git@fix_tile_url#egg=xarray_leaflet
