name: xarray-leaflet
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - requests
    - tqdm
    - scipy
    - dask
    - jupyterlab
    - git+https://github.com/davidbrochart/xarray_leaflet.git@vector#egg=xarray_leaflet
