name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [ '3.7' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      run: mamba install python=${{ matrix.python-version }} pip

    - name: Install xarray-leaflet
      run: |
        pip install .[test]

    - name: Check style
      run: |
        black --check xarray_leaflet tests
        isort --check --profile=black xarray_leaflet tests
        flake8 xarray_leaflet tests
        # mypy xarray_leaflet

    - name: Run tests
      run: |
        # TODO
        # pytest xarray_leaflet/tests -v
